[package]
name = "reproducer"
version = "0.1.0"
edition = "2018"

[lib]
name = "reproducer"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.0"
features = ["extension-module"]

[dependencies.serde]
version = "1.0.118"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.61"
